### ISSUE TITLE
Nextflow config not found

### ISSUE THREAD

**Issue by kirstyn** [lanadelrea/Katmon#1]
Receive the following error when trying to run the nextflow command on example data (from inside the CoPi directory)
`nextflow run CoPi --in_dir Samples --out_dir tes`
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/nextflow-io/CoPi/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/nextflow-io/CoPi/contents/main.nf

**Comment by lanadelrea** [comment]
Hi Kirstyn! You have to run the command at the same level as the CoPi directory, not from inside. Please let me know about further issues. Thank you so much!
