### ISSUE TITLE
concat error

### ISSUE THREAD

**Issue by eraparroyo99** [lanadelrea/Katmon#11]
N E X T F L O W  ~  version 23.10.1
Launching `CoPi/main.nf` [astonishing_mcclintock] DSL2 - revision: 9a59f5b6be
[-        ] process > concat                                     -
executor >  local (7)
[3a/69d04e] process > concat (Concatenating fasta files into ... [  0%] 0 of 1
executor >  local (7)
[3a/69d04e] process > concat (Concatenating fasta files into ... [  0%] 0 of 1
[-        ] process > pangolin                                   -
[-        ] process > nextclade                                  -
[-        ] process > lineage_assignment                         -
[-        ] process > bammix                                     -
[-        ] process > bam_filter                                 -
[a2/1c979f] process > virstrain (Identifying lineage assignme... [  0%] 0 of 3
[f9/eb738b] process > freyja (Identifying relative lineage ab... [  0%] 0 of 3
[-        ] process > freyja_demix                               -
[-        ] process > freyja_aggregate                           -
[-        ] process > freyja_plot                                -
[-        ] process > makevcf                                    -
[-        ] process > bammixplot                                 -
[-        ] process > aafplot_mutations                          -
[-        ] process > aafplot_amplicons                          -
[-        ] process > ampliconsorting_DeltaReads                 -
[-        ] process > ampliconsorting_OmicronReads               -
[-        ] process > ampliconsorting_samtools                   -
[-        ] process > ampliconsorting_bgzip                      -
[-        ] process > ampliconsorting_fasta                      -
[-        ] process > ampliconsorting_lineageAssignment_Pangolin -
[-        ] process > ampliconsorting_lineageAssignment_Nextc... -
[-        ] process > report                                     -
ERROR ~ Error executing process > 'concat (Concatenating fasta files into all_sequences.fasta)'

Caused by:
  Process `concat (Concatenating fasta files into all_sequences.fasta)` terminated with an error exit status (1)

Command executed:
executor >  local (7)
[3a/69d04e] process > concat (Concatenating fasta files into ... [100%] 1 of 1, failed: 1 ✘
[-        ] process > pangolin                                   -
[-        ] process > nextclade                                  -
[-        ] process > lineage_assignment                         -
[-        ] process > bammix                                     -
[-        ] process > bam_filter                                 -
[-        ] process > virstrain (Identifying lineage assignme... -
[-        ] process > freyja (Identifying relative lineage ab... -
[-        ] process > freyja_demix                               -
[-        ] process > freyja_aggregate                           -
[-        ] process > freyja_plot                                -
[-        ] process > makevcf                                    -
[-        ] process > bammixplot                                 -
[-        ] process > aafplot_mutations                          -
[-        ] process > aafplot_amplicons                          -
[-        ] process > ampliconsorting_DeltaReads                 -
[-        ] process > ampliconsorting_OmicronReads               -
[-        ] process > ampliconsorting_samtools                   -
[-        ] process > ampliconsorting_bgzip                      -
[-        ] process > ampliconsorting_fasta                      -
[-        ] process > ampliconsorting_lineageAssignment_Pangolin -
[-        ] process > ampliconsorting_lineageAssignment_Nextc... -
[-        ] process > report                                     -
ERROR ~ Error executing process > 'concat (Concatenating fasta files into all_sequences.fasta)'

Caused by:
  Process `concat (Concatenating fasta files into all_sequences.fasta)` terminated with an error exit status (1)

Command executed:

  cat /home/neil//home/neil/copi/input/Samples/*.fasta > all_sequences.fasta

Command exit status:
  1

Command output:
  (empty)

Command error:
  /etc/bash.bashrc: line 7: PS1: unbound variable
  /etc/bash.bashrc: line 7: PS1: unbound variable
  cat: '/home/neil//home/neil/copi/input/Samples/*.fasta': No such file or directory

Work dir:
  /home/neil/work/3a/69d04e9e46992abc79a5215be7907c

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details

**Comment by lanadelrea** [comment]
Hi sir @eraparroyo99 the scripts can already accomodate relative path instead of absolute path. 

The error is on the line 
```cat /home/neil//home/neil/copi/input/Samples/*.fasta > all_sequences.fasta```

You can adjust the input the relative path as ```copi/input/Samples/``` instead of the absolute path ```/home/neil/copi/input/Samples/```


Thank you so much!

**Comment by eraparroyo99** [comment]
changed input and output paths to relative. this is what happened:

Launching `CoPi/main.nf` [dreamy_wright] DSL2 - revision: 9a59f5b6be
[-        ] process > concat                                     -
executor >  local (9)
[48/d2f5e4] process > concat (Concatenating fasta files into ... [100%] 1 of 1 ✔
executor >  local (9)
[48/d2f5e4] process > concat (Concatenating fasta files into ... [100%] 1 of 1 ✔
executor >  local (9)
[48/d2f5e4] process > concat (Concatenating fasta files into ... [100%] 1 of 1 ✔
executor >  local (9)
[48/d2f5e4] process > concat (Concatenating fasta files into ... [100%] 1 of 1 ✔
executor >  local (12)
[48/d2f5e4] process > concat (Concatenating fasta files into ... [100%] 1 of 1 ✔
executor >  local (12)
[48/d2f5e4] process > concat (Concatenating fasta files into ... [100%] 1 of 1 ✔
[2f/0be9f4] process > pangolin (Lineage assignment using pang... [  0%] 0 of 1
[c8/f518ea] process > nextclade (Lineage assignment using nex... [100%] 1 of 1 ✔
[-        ] process > lineage_assignment                         -
[2b/b93ff0] process > bammix (Looking for positions with nucl... [  0%] 0 of 3
[-        ] process > bam_filter                                 -
[9b/110361] process > virstrain (Identifying lineage assignme... [100%] 3 of 3 ✔
[da/c64401] process > freyja (Identifying relative lineage ab... [  0%] 0 of 3
[-        ] process > freyja_demix                               -
[-        ] process > freyja_aggregate                           -
[-        ] process > freyja_plot                                -
[-        ] process > makevcf                                    -
[-        ] process > bammixplot                                 -
[-        ] process > aafplot_mutations                          -
[-        ] process > aafplot_amplicons                          -
[-        ] process > ampliconsorting_DeltaReads                 -
[-        ] process > ampliconsorting_OmicronReads               -
[-        ] process > ampliconsorting_samtools                   -
[-        ] process > ampliconsorting_bgzip                      -
[-        ] process > ampliconsorting_fasta                      -
[-        ] process > ampliconsorting_lineageAssignment_Pangolin -
[-        ] process > ampliconsorting_lineageAssignment_Nextc... -
[-        ] process > report                                     -
ERROR ~ Error executing process > 'bammix (Looking for positions with nucleotide mixtures using bammix)'

Caused by:
  Process `bammix (Looking for positions with nucleotide mixtures using bammix)` terminated with an error exit status (126)

executor >  local (12)
[48/d2f5e4] process > concat (Concatenating fasta files into ... [100%] 1 of 1 ✔
[-        ] process > pangolin (Lineage assignment using pang... -
[c8/f518ea] process > nextclade (Lineage assignment using nex... [100%] 1 of 1 ✔
[-        ] process > lineage_assignment                         -
[2b/b93ff0] process > bammix (Looking for positions with nucl... [100%] 1 of 1, failed: 1
[-        ] process > bam_filter                                 -
[9b/110361] process > virstrain (Identifying lineage assignme... [100%] 3 of 3 ✔
[-        ] process > freyja (Identifying relative lineage ab... -
[-        ] process > freyja_demix                               -
[-        ] process > freyja_aggregate                           -
[-        ] process > freyja_plot                                -
[-        ] process > makevcf                                    -
[-        ] process > bammixplot                                 -
[-        ] process > aafplot_mutations                          -
[-        ] process > aafplot_amplicons                          -
[-        ] process > ampliconsorting_DeltaReads                 -
[-        ] process > ampliconsorting_OmicronReads               -
[-        ] process > ampliconsorting_samtools                   -
[-        ] process > ampliconsorting_bgzip                      -
[-        ] process > ampliconsorting_fasta                      -
[-        ] process > ampliconsorting_lineageAssignment_Pangolin -
[-        ] process > ampliconsorting_lineageAssignment_Nextc... -
[-        ] process > report                                     -
ERROR ~ Error executing process > 'bammix (Looking for positions with nucleotide mixtures using bammix)'

Caused by:
  Process `bammix (Looking for positions with nucleotide mixtures using bammix)` terminated with an error exit status (126)

Command executed:

  bammix.py nextclade.tsv /home/neil/copi/input/Samples

Command exit status:
  126

Command output:
  (empty)

Command error:
  /etc/bash.bashrc: line 7: PS1: unbound variable
  .command.sh: line 2: /home/neil/CoPi/bin/bammix.py: Permission denied

Work dir:
  /home/neil/work/2a/848b48b1a47e5c2f1565dd5781d84e

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details

**Comment by macarmencorp** [comment]
> Command error:
/etc/bash.bashrc: line 7: PS1: unbound variable
.command.sh: line 2: /home/neil/CoPi/bin/bammix.py: Permission denied

I tried chmod and it kinda worked :)

**Comment by lanadelrea** [comment]
Hi sir @eraparroyo99 it looks like a permission error. I edited the permission on my end, kindly see if the pipeline works properly this time. Thank you so much!

**Comment by eraparroyo99** [comment]
updated local copy of copi using git clone
used relative paths in nextflow command (previously tried absolute path, but result was worse then this)
ended up with:

N E X T F L O W  ~  version 23.10.1
Launching `CoPi/main.nf` [furious_kare] DSL2 - revision: 9a59f5b6be
[-        ] process > concat                                     -
executor >  local (9)
[5e/2bd7d2] process > concat (Concatenating fasta files into ... [100%] 1 of 1 ✔
[05/052056] process > pangolin (Lineage assignment using pang... [  0%] 0 of 1
[59/39b872] process > nextclade (Lineage assignment using nex... [  0%] 0 of 1
[-        ] process > lineage_assignment                         -
[-        ] process > bammix                                     -
[-        ] process > bam_filter                                 -
[36/c7469c] process > virstrain (Identifying lineage assignme... [  0%] 0 of 3
[41/29f255] process > freyja (Identifying relative lineage ab... [  0%] 0 of 3
[-        ] process > freyja_demix                               -
[-        ] process > freyja_aggregate                           -
[-        ] process > freyja_plot                                -
[-        ] process > makevcf                                    -
[-        ] process > bammixplot                                 -
[-        ] process > aafplot_mutations                          -
[-        ] process > aafplot_amplicons                          -
[-        ] process > ampliconsorting_DeltaReads                 -
[-        ] process > ampliconsorting_OmicronReads               -
[-        ] process > ampliconsorting_samtools                   -
[-        ] process > ampliconsorting_bgzip                      -
[-        ] process > ampliconsorting_fasta                      -
[-        ] process > ampliconsorting_lineageAssignment_Pangolin -
[-        ] process > ampliconsorting_lineageAssignment_Nextc... -
[-        ] process > report                                     -

[process exited with code 1 (0x00000001)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
