### ISSUE TITLE
freyja issue?

### ISSUE THREAD

**Issue by eraparroyo99** [lanadelrea/Katmon#13]
reinstalled my wsl ubuntu from scratch
reinstalled anaconda, python, docker, nextflow

result:
N E X T F L O W  ~  version 23.10.1
Launching `CoPi/main.nf` [sick_banach] DSL2 - revision: 9a59f5b6be
executor >  local (9)
executor >  local (9)
executor >  local (9)
[ca/4007fc] process > concat (Concatenating fasta files into all_se... [100%] 1 of 1 ✔
[64/eb1e8c] process > pangolin (Lineage assignment using pangolin t... [  0%] 0 of 1
[8f/993164] process > nextclade (Lineage assignment using nextclade)   [  0%] 0 of 1
[-        ] process > lineage_assignment                               -
[-        ] process > bammix                                           -
[-        ] process > bam_filter                                       -
[be/65ce08] process > virstrain (Identifying lineage assignment for... [  0%] 0 of 3
[81/8598ea] process > freyja (Identifying relative lineage abundanc... [  0%] 0 of 3
[-        ] process > freyja_demix                                     -
[-        ] process > freyja_aggregate                                 -
[-        ] process > freyja_plot                                      -
[-        ] process > makevcf                                          -
[-        ] process > bammixplot                                       -
[-        ] process > aafplot_mutations                                -
[-        ] process > aafplot_amplicons                                -
[-        ] process > ampliconsorting_DeltaReads                       -
[-        ] process > ampliconsorting_OmicronReads                     -
[-        ] process > ampliconsorting_samtools                         -
[-        ] process > ampliconsorting_bgzip                            -
[-        ] process > ampliconsorting_fasta                            -
[-        ] process > ampliconsorting_lineageAssignment_Pangolin       -
[-        ] process > ampliconsorting_lineageAssignment_Nextclade      -
[-        ] process > report                                           -
ERROR ~ Error executing process > 'freyja (Identifying relative lineage abundances of samples to see potential coinfection)'

Caused by:
  Process `freyja (Identifying relative lineage abundances of samples to see potential coinfection)` terminated with an error exit status (126)

Command executed:

  freyja variants barcode08.bam         --variants barcode08_variants.tsv         --depths barcodeexecutor >  local (9)
[ca/4007fc] process > concat (Concatenating fasta files into all_se... [100%] 1 of 1 ✔
[64/eb1e8c] process > pangolin (Lineage assignment using pangolin t... [100%] 1 of 1, failed: 1 ✘
[8f/993164] process > nextclade (Lineage assignment using nextclade)   [100%] 1 of 1, failed: 1 ✘
[-        ] process > lineage_assignment                               -
[-        ] process > bammix                                           -
[-        ] process > bam_filter                                       -
[be/65ce08] process > virstrain (Identifying lineage assignment for... [100%] 3 of 3, failed: 3 ✘
[10/6fd6f1] process > freyja (Identifying relative lineage abundanc... [100%] 2 of 2, failed: 2
[-        ] process > freyja_demix                                     -
[-        ] process > freyja_aggregate                                 -
[-        ] process > freyja_plot                                      -
[-        ] process > makevcf                                          -
[-        ] process > bammixplot                                       -
[-        ] process > aafplot_mutations                                -
[-        ] process > aafplot_amplicons                                -
[-        ] process > ampliconsorting_DeltaReads                       -
[-        ] process > ampliconsorting_OmicronReads                     -
[-        ] process > ampliconsorting_samtools                         -
[-        ] process > ampliconsorting_bgzip                            -
[-        ] process > ampliconsorting_fasta                            -
[-        ] process > ampliconsorting_lineageAssignment_Pangolin       -
[-        ] process > ampliconsorting_lineageAssignment_Nextclade      -
[-        ] process > report                                           -
ERROR ~ Error executing process > 'freyja (Identifying relative lineage abundances of samples to see potential coinfection)'

Caused by:
  Process `freyja (Identifying relative lineage abundances of samples to see potential coinfection)` terminated with an error exit status (126)

Command executed:

  freyja variants barcode08.bam         --variants barcode08_variants.tsv         --depths barcode08_depth.tsv         --ref /home/neil/CoPi/assets/sars-cov-2/reference-sequence.fasta

Command exit status:
  126

Command output:
  (empty)

Command error:
  /etc/bash.bashrc: line 7: PS1: unbound variable
  docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied.
  See 'docker run --help'.

Work dir:
  /home/neil/work/21/914b563ccb2c24c7710fcbcb6beb26

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details

**Comment by lanadelrea** [comment]
The docker is not online sir. Kindly check if docker is working or you can also use the conda option to run the pipeline. Thanks po!
