### ISSUE TITLE
2024-04-11 copi issue nmy

### ISSUE THREAD

**Issue by eraparroyo99** [lanadelrea/Katmon#2]
ERROR ~ Error executing process > 'virstrain (Identifying lineage assignment for barcode08 using Virstrain)'

Caused by:
  Process `virstrain (Identifying lineage assignment for barcode08 using Virstrain)` terminated with an error exit status (2)

Command executed:

  python /home/neil/CoPi/bin/VirStrain/VirStrain.py         -i /home/neil/copi/input/Samples/barcode08.fastq         -d /home/neil/CoPi/bin/VirStrain/Custom_DB         -o /home/neil/copi/output/03-Virstrain/barcode08

Command exit status:
  2

Command output:
  (empty)

Command error:
  /etc/bash.bashrc: line 7: PS1: unbound variable
  /etc/bash.bashrc: line 7: PS1: unbound variable
  python: can't open file '/home/neil/CoPi/bin/VirStrain/VirStrain.py': [Errno 2] No such file or directory

Work dir:
  /home/neil/work/13/fb597b8406192442e42da72301faa8

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details

**Comment by lanadelrea** [comment]
Hi sir Neil!

The database and scripts for VirStrain were missing but I have already updated the repository. May I kindly ask for you to run the pipeline again and post any issues encountered. Thank you so much!

**Comment by lanadelrea** [comment]
Hi sir Neil! I made a docker container for VirStrain and the pipeline should run smoothly now. Kindly clone the pipeline again and test. Thank you so much!
